### ISSUE TITLE
Remove print statement from spice_error()

### ISSUE THREAD

**Issue by grahamkerr** [solo-spice/sospice#37]
This is minor, but can the print(data.unit) statement on line 40 of spice_error() be removed or moved inside the verbose flag?

**Comment by ebuchlin** [comment]
Yes, sure! It's in commit 18abb28a1461e8b77e56c7c66c8f5e9cf802642b and it will part of the next release.

**Comment by ebuchlin** [comment]
Now in released version 0.0.8.
